server {
    listen 80;
    server_name localhost;

    # React Static Assets & Single Page Application routing
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # API endpoint served by React Nginx Pod returning Pod Hostname & Status
    location /api/pod-info {
        default_type application/json;
        add_header Access-Control-Allow-Origin *;
        return 200 '{"status":"ONLINE","pod":"$hostname","message":"Hello from React Kubernetes Pod!","timestamp":"$time_iso8601","gateway":"Kong API Gateway"}';
    }
}
